// Code generated by "codegen ./errcode"; DO NOT EDIT.

package errcode

// init register error codes defines in `github.com/marmotedu/errors`
func init() {
	register(ErrSuccess, 200, "OK")
	register(ErrUnknown, 500, "Internal server error")
	register(ErrBadParams, 400, "Bad request parameters")
	register(ErrNotFound, 404, "Not found")
	register(ErrPasswordInvalid, 401, "Password invalid")
	register(ErrHeaderInvalid, 401, "Authorization header invalid")
	register(ErrSignatureInvalid, 401, "Signature invalid")
	register(ErrTokenInvalid, 401, "Token invalid")
	register(ErrTokenExpired, 401, "Token expired")
	register(ErrPermissionDenied, 403, "Permission denied")
	register(ErrDatabase, 500, "Database error")
}
